### ISSUE TITLE
Enhance logging

### ISSUE THREAD

**Issue by wcarthur** [GeoscienceAustralia/hazimp#7]
Currently no logging messages are recorded in `HazImp`, making it difficult to track what's happening. Recommend adding logging statements of various levels through the code to assist other users with understanding what's happening

**Comment by wcarthur** [comment]
In progress. Ongoing development should include logging statements using the standard `logging` library.

**Comment by benjimin** [comment]
Now streaming to stderr such messages as:
```
INFO:core_hazimp.pipeline:Executing LoadCsvExposure
INFO:core_hazimp.pipeline:Executing LoadRaster
INFO:core_hazimp.pipeline:Executing LoadXmlVulnerability
INFO:core_hazimp.pipeline:Executing SimpleLinker
INFO:core_hazimp.pipeline:Executing SelectVulnFunction
INFO:core_hazimp.pipeline:Executing LookUp
INFO:core_hazimp.pipeline:Executing MultipleDimensionMult
INFO:core_hazimp.pipeline:Executing SaveExposure
```
(Aside, waiting for pandas to import is sometimes slower than the rest of the process. This may be improved in later python versions.)
